using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using DailyLifeMate.Domain.Interfaces;
using DailyLifeMate.Engine.Features.Series.Models;

namespace DailyLifeMate.Tests.Integration.Common;

public class FakeAnimeMetadataProvider : IAnimeMetadataProvider
{
    // Public constants and read-only fields for test assertions
    public const string FakeSynopsis = "This is a predictable synopsis generated by the Fake Provider for testing.";
    public const string FakeImageUrl = "http://fake-image-url.com/image.jpg";
    public const int FakeTotalEpisodes = 24;
    public const string FakeAiringStatus = "Finished Airing";

    // Lists and Dates must be static readonly
    public static readonly List<string> FakeGenres = new() { "Action", "Test-Genre" };
    public static readonly DateTime FakeReleasedOn = new(2020, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    public Task<AnimeMetadata?> GetAnimeInfoAsync(string name)
    {
        // Simulate a "Not Found" scenario
        if (name.Contains("NotFound"))
        {
            return Task.FromResult<AnimeMetadata?>(null);
        }

        // Simulate a successful Jikan API response
        var fakeMetadata = new AnimeMetadata
        {
            Title = name,
            Synopsis = FakeSynopsis,
            ImageUrl = FakeImageUrl,
            TotalEpisodes = FakeTotalEpisodes,
            Status = FakeAiringStatus,
            Genres = FakeGenres,
            ReleasedOn = FakeReleasedOn
        };

        return Task.FromResult<AnimeMetadata?>(fakeMetadata);
    }
}